# Generated by Django 5.2.2 on 2025-06-17 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nom_complet", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetailService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("detail", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=200)),
                ("disponible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Temoignage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("post_nom", models.CharField(max_length=30)),
                ("temoignage", models.TextField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
