# Generated by Django 5.2.2 on 2025-06-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailservice",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="app_sk.service",
            ),
        ),
        migrations.AlterField(
            model_name="detailservice",
            name="detail",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="temoignage",
            name="temoignage",
            field=models.TextField(),
        ),
    ]
