# Generated by Django 5.2.2 on 2025-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='pubic',
            field=models.BooleanField(default=False),
        ),
    ]
