# Generated by Django 5.2.2 on 2025-06-19 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sk", "0002_detailservice_service_alter_detailservice_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="prix1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="prix2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DemanderServicer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("post_nom", models.CharField(max_length=30)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandeservices",
                        to="app_sk.service",
                    ),
                ),
            ],
        ),
    ]
