# Generated by Django 5.2.2 on 2025-07-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sk', '0002_service_image_temoignage_pubic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phrasePhare',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
